server:
  port: 8006
spring:
  application:
    name: cloud-provider-payment #consul 服务实例名称
  cloud:
    consul:
      #consul注册中心连接地址
      host: 192.168.179.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}
