server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka注册中心名称
   # hostname: eureka-server7001 #eureka注册中心名称
  #是否向注册中心注册自己
  client:
    register-with-eureka: false
  #是否检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/

  server:
    enable-self-preservation: false #关闭自我保护机制，一旦有服务宕机，超过接收心跳时间就移除
    eviction-interval-timer-in-ms: 3000  #清理无效节服务的时间间隔

logging:
  level:
    com.netflix: warn #调整日志级别，不然会一直打印Eviction Timer逐出计时器的日志信息